services:
  stt-to-notion:
    image: crpi-q7c6zhbv16qchx4n.cn-hangzhou.personal.cr.aliyuncs.com/chaoliu719/stt-to-notion:latest
    container_name: stt-to-notion
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
